In [1]:
import pandas as pd

In [2]:
## fazer carregamento do arquivo csv. Pandas ira retonar um Dataframe
df = pd.read_csv("ocorrencia3.csv", sep=",", infer_datetime_format=True, parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80436,80436,80436,80436,80436,INCIDENTE,PALMAS,TO,SBPJ,2021-12-09,22:10:00,SIM,FINALIZADA,0,1,NÃO
1,53472,53472,53472,53472,53472,ACIDENTE,COLINAS DO TOCANTINS,TO,****,2015-07-28,21:05:00,***,NaN,0,1,NÃO
2,78800,78800,78800,78800,78800,ACIDENTE,PALMAS,TO,SDNB,2017-08-20,20:30:00,SIM,FINALIZADA,0,1,NÃO
3,79690,79690,79690,79690,79690,INCIDENTE GRAVE,PORTO NACIONAL,TO,SWEJ,2020-11-24,20:00:00,SIM,FINALIZADA,0,1,NÃO
4,50531,50531,50531,50531,50531,INCIDENTE,GURUPI,TO,****,2013-12-08,20:00:00,***,FINALIZADA,0,1,NÃO
5,79636,79636,79636,79636,79636,ACIDENTE,PALMAS,TO,****,2020-10-29,20:00:00,SIM,ATIVA,0,1,NÃO
6,53233,53233,53233,53233,53233,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2015-04-15,19:31:00,SIM,FINALIZADA,0,1,SIM
7,45731,45731,45731,45731,45731,ACIDENTE,PALMAS,TO,****,2012-03-31,19:21:00,SIM,FINALIZADA,0,1,NÃO
8,50952,50952,50952,50952,50952,ACIDENTE,ARAGUAÍNA,TO,SWGN,2014-02-19,19:21:00,***,FINALIZADA,0,1,NÃO
9,60881,60881,60881,60881,60881,ACIDENTE,CRISTALÂNDIA,TO,****,2016-03-13,19:00:00,SIM,FINALIZADA,0,1,SIM

In [3]:
df.loc[1:3, 'ocorrencia_cidade']

1    COLINAS DO TOCANTINS
2                  PALMAS
3          PORTO NACIONAL
Name: ocorrencia_cidade, dtype: object

In [4]:
df.codigo_ocorrencia.is_unique

True

In [7]:
df.set_index('codigo_ocorrencia', inplace=True)

In [8]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,
80436,80436,80436,80436,80436,INCIDENTE,PALMAS,TO,SBPJ,2021-12-09,22:10:00,SIM,FINALIZADA,0,1,NÃO
53472,53472,53472,53472,53472,ACIDENTE,COLINAS DO TOCANTINS,TO,****,2015-07-28,21:05:00,***,NaN,0,1,NÃO
78800,78800,78800,78800,78800,ACIDENTE,PALMAS,TO,SDNB,2017-08-20,20:30:00,SIM,FINALIZADA,0,1,NÃO
79690,79690,79690,79690,79690,INCIDENTE GRAVE,PORTO NACIONAL,TO,SWEJ,2020-11-24,20:00:00,SIM,FINALIZADA,0,1,NÃO
50531,50531,50531,50531,50531,INCIDENTE,GURUPI,TO,****,2013-12-08,20:00:00,***,FINALIZADA,0,1,NÃO

In [9]:
df.reset_index(drop=True, inplace=True)

In [10]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80436,80436,80436,80436,INCIDENTE,PALMAS,TO,SBPJ,2021-12-09,22:10:00,SIM,FINALIZADA,0,1,NÃO
1,53472,53472,53472,53472,ACIDENTE,COLINAS DO TOCANTINS,TO,****,2015-07-28,21:05:00,***,NaN,0,1,NÃO
2,78800,78800,78800,78800,ACIDENTE,PALMAS,TO,SDNB,2017-08-20,20:30:00,SIM,FINALIZADA,0,1,NÃO
3,79690,79690,79690,79690,INCIDENTE GRAVE,PORTO NACIONAL,TO,SWEJ,2020-11-24,20:00:00,SIM,FINALIZADA,0,1,NÃO
4,50531,50531,50531,50531,INCIDENTE,GURUPI,TO,****,2013-12-08,20:00:00,***,FINALIZADA,0,1,NÃO

## LIMPEZA DE DADOS

In [15]:
## atribuir a celula 'ocorrencia_aerodromo' que possui valores '****' valor não disponivel
df.loc[df.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80436,80436,80436,80436,INCIDENTE,PALMAS,TO,SBPJ,2021-12-09,22:10:00,SIM,FINALIZADA,0,1,NÃO
1,53472,53472,53472,53472,ACIDENTE,COLINAS DO TOCANTINS,TO,<NA>,2015-07-28,21:05:00,***,NaN,0,1,NÃO
2,78800,78800,78800,78800,ACIDENTE,PALMAS,TO,SDNB,2017-08-20,20:30:00,SIM,FINALIZADA,0,1,NÃO
3,79690,79690,79690,79690,INCIDENTE GRAVE,PORTO NACIONAL,TO,SWEJ,2020-11-24,20:00:00,SIM,FINALIZADA,0,1,NÃO
4,50531,50531,50531,50531,INCIDENTE,GURUPI,TO,<NA>,2013-12-08,20:00:00,***,FINALIZADA,0,1,NÃO

In [17]:
## substituir valores\
df.replace(['***', '###!', '####', '****', '*****', 'NULL'], pd.NA, inplace=True)
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,80436,80436,80436,80436,INCIDENTE,PALMAS,TO,SBPJ,2021-12-09,22:10:00,SIM,FINALIZADA,0,1,NÃO
1,53472,53472,53472,53472,ACIDENTE,COLINAS DO TOCANTINS,TO,<NA>,2015-07-28,21:05:00,<NA>,NaN,0,1,NÃO
2,78800,78800,78800,78800,ACIDENTE,PALMAS,TO,SDNB,2017-08-20,20:30:00,SIM,FINALIZADA,0,1,NÃO
3,79690,79690,79690,79690,INCIDENTE GRAVE,PORTO NACIONAL,TO,SWEJ,2020-11-24,20:00:00,SIM,FINALIZADA,0,1,NÃO
4,50531,50531,50531,50531,INCIDENTE,GURUPI,TO,<NA>,2013-12-08,20:00:00,<NA>,FINALIZADA,0,1,NÃO

In [20]:
#verificar se a celula tem valor disponivel ou não
df.isna()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5161,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5162,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5163,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5164,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5165,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False

In [21]:
# somatorio de valores não informados, por coluna
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_aerodromo              1904
ocorrencia_dia                       0
ocorrencia_hora                      0
investigacao_aeronave_liberada    1777
investigacao_status                257
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64